version: '3'

services:
  db:
    container_name: library_db
    image: postgres:14.1
    volumes: 
      - storage_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - library_back/.env
    network_mode: host

  app:
    container_name: library_backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    build: library_back/
    network_mode: host
    ports:
      - 8000:8000

  front:
    container_name: library_front
    command: npm start
    depends_on:
      - app
    build: library_front/
    network_mode: host
    ports:
      - 3000:3000

  nginx:
    container_name: library_nginx
    image: nginx:latest
    depends_on:
      - front
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    network_mode: host
    
volumes:
  storage_db:
