name: Test and Lint Backend

on:
  push:
    branches: [ "main", "continuous_integration" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: library_db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd library_back/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        cd library_back/
        python manage.py makemigrations
        python manage.py migrate
      env:
        POSTGRES_DB: library_db_test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
    - name: Run Tests
      run: |
        cd library_back/
        python manage.py test
      env:
        POSTGRES_DB: library_db_test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432